version: '2'

services:
  app:
    image: 'bank_service'
    build:
      context: ../../..
    container_name: bank_service
    ports:
      - "8200:8000"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bank_emulator
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create
      - SPRING_JPA_properties_hibernate_dialect=org.hibernate.dialect.PostgreSQLDialect

  db:
    image: 'bitnami/postgresql'
    container_name: postgres_bank_service
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
